Updates to index.ts and implementation for SalesOrderDetails FE
zixuan97/algotech-fe pull request #127
Opened 2022-09-24 17:33 UTC by zixuan97

feat: Update sales order, can add/remove items into SalesOrderItems[]
fix: Update of index.ts to sync with BE

2022-09-24 17:35 UTC, zixuan97 commented
They'll need the types.ts updated file, I'll refactor after I'm done implementing the routes to connect to BE

2022-09-25 03:14 UTC, danielonges requested changes
need to refactor ah, if not we will accumulate tech debt as we go along

2022-09-25 03:14 UTC, danielonges commented on src/pages/sales/SalesOrderDetails.tsx
> +                'Sales Order does nto exist. You will be redirected back to the Sales Order Overview page.'
typo

2022-09-25 03:14 UTC, danielonges commented on src/pages/sales/SalesOrderDetails.tsx
> +            switch (salesOrder.orderStatus) {
this whole switch statement can be refactored by including the OrderStatus as a value in each object within the steps array, then finding the index of the object that matches the value

`const steps = [{
    label: 'Order Placed',
    value: OrderStatus.CREATED,
    icon: <ReceiptLongRounded sx={{ fontSize: 35 }} />,
    nextAction: 'Confirm Payment'
  },...`

then afterwards,
```suggestion
            setActiveStep(steps.findIndex(step => step.value === salesOrder.orderStatus)
```

2022-09-25 03:14 UTC, danielonges commented on src/pages/sales/SalesOrderDetails.tsx
>      switch (salesOrder?.orderStatus) {
this switch statement also can be refactored
```suggestion
    if (activeStep < steps.length - 1) {
      setActiveStep(prev => prev + 1);
      const newStatus = steps[activeStep + 1].value;
      if (newStatus === OrderStatus.PREPARED) {
        setSalesOrder(order => order && {...order, orderStatus: newStatus, salesOrderItems: editSalesOrderItems });
        updateSalesOrder();
      } else {
        setSalesOrder(order => order && {...order, orderStatus: newStatus });
      }
    }
```

2022-09-25 03:14 UTC, danielonges commented on src/services/salesService.ts
> +  console.log('salesOrder HEREEEEEE', salesOrder);
remove this console log

2022-09-25 04:34 UTC, closed without merging